#ifndef ROBOT_PINOUT
#define ROBOT_PINOUT

#define MOTOR_LEFT_PIN_A 10
#define MOTOR_LEFT_PIN_B 11
#define MOTOR_LEFT_ENCODER_1 18
#define MOTOR_LEFT_ENCODER_2 19

#define MOTOR_RIGHT_PIN_A 12
#define MOTOR_RIGHT_PIN_B 13
#define MOTOR_RIGHT_ENCODER_1 20
#define MOTOR_RIGHT_ENCODER_2 21

#define BUMPER_LEFT 6
#define BUMPER_RIGHT 7

#define FLOOR_S_L1 3
#define FLOOR_S_L2 5
#define FLOOR_S_R1 2
#define FLOOR_S_R2 4

#endif
